version: 2
jobs:
  build:
    branches:
      only:
        - master #Only building for master branch pushes
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          name: Install packages
          command: sudo apt-get update && sudo apt-get install wget zip unzip -y
      - run:
          name: Install awscli
          command: sudo pip install awscli
      - run:
          name: Install Lambda function prerequisites
          command: sudo pip install -r scripts/requirements.txt
